### ISSUE TITLE
reqMkdData snapshot not working

### ISSUE THREAD

**Issue by JohannesEmm** [joshuaulrich/IBrokers#47]
### Description

reqMkdData snapshot not working

### Expected behavior

Simple snapshot generation throws this error
Error in reqMktData(tws, contract, snapshot = T) : 
  Snapshot not working (?)

### Minimal, reproducible example

```r
contract <- twsEquity("QQQQ","SMART","ISLAND")
reqMktData(tws, contract, snapshot = T)
```

### Session Info

```r
[Insert your sessionInfo() output]
```

On a more general level, is this package working with the latest API?

**Comment by joshuaulrich** [comment]
Thanks for the report! I added that error when I was trying to merge [these insane PR changes](https://github.com/joshuaulrich/IBrokers/pull/9) because I couldn't confirm snapshots were working at the time.

> On a more general level, is this package working with the latest API?

No, IBrokers does not support the latest TWS API versions. See [rib](https://github.com/lbilli/rib) for an alternative and up-to-date implementation of the latest API versions.
